version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data  # Mount data directory for persistent storage
